Models/Pessoa.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Sistema.Models
{
    public class Pessoa
    {        
        public int Id { get; set;}
        [Required(ErrorMessage ="Digite o nome!")]
        public string NomeCompleto { get; set;}
        [Required]        
        public DateTime DataNascimento { get; set;}
        [Required(ErrorMessage = "Digite a renda!")]
        public string RendaValor { get; set;}
        [Required(ErrorMessage = "Digite o CPF!")]
        public string CPF { get; set;}
    }
}

Controllers/PessoaController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Sistema.Models;
using Sistema.Repositorio;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace Sistema.Controllers
{
    public class PessoaController : Controller
    {
        private readonly IPessoaRepositorio _pessoaRepositorio;

        public PessoaController(IPessoaRepositorio pessoaRepositorio)
        {
            _pessoaRepositorio = pessoaRepositorio;
        }

        public IActionResult Index()
        {
            //var pessoas = _pessoaRepositorio.BuscarTodos();

            var pessoas = BuscarTodasPessoasAPI();

            return View(pessoas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Pessoa pessoa)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //Entity Framework
                    //var createPessoas = _pessoaRepositorio.Adicionar(pessoa);

                    //API
                    var create = CreateAPI(pessoa);
                    TempData["MensagemSucesso"] = "Cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(pessoa);
            }
            catch(Exception ex)
            {
                TempData["MensagemErro"] = $"Erro: {ex.Message}";
                return RedirectToAction("Index");
            }
        }


        public IActionResult Edit(int id)
        {
            Pessoa pessoa = _pessoaRepositorio.BuscarPorId(id);

            return View(pessoa);
        }

        [HttpPost]
        public IActionResult Edit(Pessoa pessoa)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    var EditApi = EditAPI(pessoa);

                    if(EditApi != null)
                    {
                        TempData["MensagemSucesso"] = "Alterado com sucesso!";
                        return RedirectToAction("Index");
                    }
                }

                return View("Editar", pessoa);
            }
            catch(Exception ex)
            {
                TempData["MensagemErro"] = $"Erro: {ex.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Delete(int id)
        {
            Pessoa pessoa = _pessoaRepositorio.BuscarPorId(id);
            return View(pessoa);
        }

        public IActionResult Apagar (int id)
        {
            try
            {
                Pessoa pessoa = _pessoaRepositorio.BuscarPorId(id);

                if(pessoa != null)
                {
                    var apagar = DeleteAPI(pessoa);

                    if (apagar == true)
                    {
                        TempData["MensagemSucesso"] = "Deletado com sucesso!";
                    }
                    else
                    {
                        TempData["MensagemErro"] = "Erro ao deletar!";
                    }
                }

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                TempData["MensagemErro"] = $"Erro: {ex.Message}";
                return RedirectToAction("Index");
            }
        }


        #region API
        public List<Pessoa> BuscarTodasPessoasAPI()
        {
            try
            {
                var request = (HttpWebRequest)WebRequest.Create("https://localhost:44373/api/Pessoa/BuscarTodasPessoas");

                request.ContentType = "application/json";
                request.Method = "GET";
                request.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip; //compressed answers

                var contentPost = string.Empty;

                using (var response = (HttpWebResponse)request.GetResponse())
                using (var stream = response.GetResponseStream())
                using (var sr = new StreamReader(stream))
                    contentPost = sr.ReadToEnd();
                                                            //null values                                 //unknow properties
                var settings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Ignore };
                var ret = JsonConvert.DeserializeObject<List<Pessoa>>(contentPost, settings);

                return ret;
            }
            catch (Exception ex)
            {
                Console.WriteLine(string.Format("Erro:", ex.Message));
                return null;
            }
        }

        public Pessoa CreateAPI(Pessoa model)
        {
            try
            {
                var request = (HttpWebRequest)WebRequest.Create("https://localhost:44373/api/Pessoa/Create");

                request.ContentType = "application/json";
                request.Method = "POST";
                request.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip;

                using (var streamWriter = new StreamWriter(request.GetRequestStream()))
                {
                    string json = JsonConvert.SerializeObject(model);

                    streamWriter.Write(json);
                    streamWriter.Flush();
                    streamWriter.Close();
                }

                var contentPost = string.Empty;

                using (var response = (HttpWebResponse)request.GetResponse())
                using (var stream = response.GetResponseStream())
                using (var sr = new StreamReader(stream))
                    contentPost = sr.ReadToEnd();

                var settings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Ignore };
                var ret = JsonConvert.DeserializeObject<Pessoa>(contentPost, settings);

                return ret;
            }
            catch (Exception ex)
            {
                Console.WriteLine(string.Format("Erro:", ex.Message));
                return null;
            }
        }
        
        public Pessoa EditAPI(Pessoa model)
        {
            try
            {
                var request = (HttpWebRequest)WebRequest.Create("https://localhost:44373/api/Pessoa/Edit");

                request.ContentType = "application/json";
                request.Method = "PUT";
                request.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip;

                using (var streamWriter = new StreamWriter(request.GetRequestStream()))
                {
                    string json = JsonConvert.SerializeObject(model);

                    streamWriter.Write(json);
                    streamWriter.Flush();
                    streamWriter.Close();
                }

                var contentPost = string.Empty;

                using (var response = (HttpWebResponse)request.GetResponse())
                using (var stream = response.GetResponseStream())
                using (var sr = new StreamReader(stream))
                    contentPost = sr.ReadToEnd();

                var settings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Ignore };
                var ret = JsonConvert.DeserializeObject<Pessoa>(contentPost, settings);
                
                return ret;
            }
            catch (Exception ex)
            {
                Console.WriteLine(string.Format("Erro:", ex.Message));
                return null;
            }
        }

        public bool DeleteAPI(Pessoa model)
        {
            try
            {
                var request = (HttpWebRequest)WebRequest.Create("https://localhost:44373/api/Pessoa/Delete");

                request.ContentType = "application/json";
                request.Method = "DELETE";
                request.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip;

                using (var streamWriter = new StreamWriter(request.GetRequestStream()))
                {
                    string json = JsonConvert.SerializeObject(model);

                    streamWriter.Write(json);
                    streamWriter.Flush();
                    streamWriter.Close();
                }

                var contentPost = string.Empty;

                using (var response = (HttpWebResponse)request.GetResponse())
                using (var stream = response.GetResponseStream())
                using (var sr = new StreamReader(stream))
                    contentPost = sr.ReadToEnd();

                return true;
            }
            catch (Exception ex)
            {                
                return false;
            }
        }


        #endregion
    }
}

Views/Pessoa/Create.cshtml
@model Pessoa;

@{
    ViewData["Title"] = "Create";
}

<div class="text-center">
    <h1 class="display-4">Create Pessoa</h1>
</div>

<form asp-controller="Pessoa" asp-action="Create" method="post">
    <div class="form-group">
        <label for="nome" class="form-label">Nome:</label>
        <input type="text" asp-for="NomeCompleto" class="form-control" placeholder="Digite o nome">
        @Html.ValidationMessageFor(x => x.NomeCompleto, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="nascimento" class="form-label">Data de Nascimento:</label>
        <input type="date" id="data" asp-for="DataNascimento" class="form-control" placeholder="Digite a data de nascimento">
        @Html.ValidationMessageFor(x => x.DataNascimento, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="renda" class="form-label">Renda:</label>
        <input type="text" id="renda" asp-for="RendaValor" class="form-control" placeholder="Digite a renda">
        @Html.ValidationMessageFor(x => x.RendaValor, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="cpf" class="form-label">CPF:</label>
        <input type="text" id="cpf" asp-for="CPF" class="form-control" placeholder="Digite o CPF">
        @Html.ValidationMessageFor(x => x.CPF, "", new { @class = "text-danger" })
    </div>

    <br />
    <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Pessoa" asp-action="Index" role="button">Voltar</a>
</form>

@*Formatação de CPF*@
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#cpf').on('input', function () {
            var cpf = $(this).val();
            cpf = cpf.replace(/\D/g, ''); // Removendo todos os caracteres não numéricos

            if (cpf.length > 11) {
                cpf = cpf.slice(0, 11); // Limita o tamanho máximo do CPF a 11 caracteres
            }

            // Formatação do CPF
            cpf = cpf.replace(/(\d{3})(\d)/, '$1.$2');
            cpf = cpf.replace(/(\d{3})(\d)/, '$1.$2');
            cpf = cpf.replace(/(\d{3})(\d{1,2})$/, '$1-$2');

            // Atualiza o valor do campo de entrada
            $(this).val(cpf);
        });

        $("#renda").on("input", function () {
            var valor = $(this).val();

            // Remove qualquer caractere que não seja número
            valor = valor.replace(/[^0-9]/g, '');

            // Atualiza o valor do campo com a versão filtrada
            $(this).val(valor);
        });
    });
</script>

Views/Pessoa/Delete.cshtml
@model Pessoa

@{
    ViewData["Title"] = "Delete";
}

<div class="text-center">
    <h1 class="display-4">Confirma a exclusão de @Model.NomeCompleto?</h1>
</div>
<br />

<form asp-controller="Pessoa" asp-action="Edit" method="post">

    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="nome" class="form-label">Nome:</label>
        <input type="text" asp-for="NomeCompleto" class="form-control" placeholder="Digite o nome" disabled>
        @Html.ValidationMessageFor(x => x.NomeCompleto, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="nascimento" class="form-label">Data de Nascimento:</label>
        <input type="date" asp-for="DataNascimento" class="form-control" placeholder="Digite a data de nascimento" disabled>
        @Html.ValidationMessageFor(x => x.DataNascimento, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="renda" class="form-label">Renda:</label>
        <input type="text" asp-for="RendaValor" class="form-control" placeholder="Digite a renda" disabled>
        @Html.ValidationMessageFor(x => x.RendaValor, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="cpf" class="form-label">CPF:</label>
        <input type="text" asp-for="CPF" id="cpf" class="form-control" placeholder="Digite o CPF" disabled>
        @Html.ValidationMessageFor(x => x.CPF, "", new { @class = "text-danger" })
    </div>
</form>

<br />

<a class="btn btn-danger btn-block" href="@Url.Action("Apagar", "Pessoa", new { Model.Id })">Confirmar Exclusão</a>
<a class="btn btn-secondary btn-block" href="@Url.Action("Index", "Pessoa")">Cancelar Exclusão</a>

Views/Pessoa/Edit.cshtml
@model Pessoa

@{
    ViewData["Title"] = "Edit - Pessoa";
}

<div class="text-center">
    <h1 class="display-4">Edit Pessoa</h1>
</div>

<form asp-controller="Pessoa" asp-action="Edit" method="post">

    <input type="hidden" asp-for="Id"/>

    <div class="form-group">
        <label for="nome" class="form-label">Nome:</label>
        <input type="text" asp-for="NomeCompleto" class="form-control" placeholder="Digite o nome">
        @Html.ValidationMessageFor(x => x.NomeCompleto, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="nascimento" class="form-label">Data de Nascimento:</label>
        <input type="date" asp-for="DataNascimento" class="form-control" placeholder="Digite a data de nascimento">
        @Html.ValidationMessageFor(x => x.DataNascimento, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="renda" class="form-label">Renda:</label>
        <input id="renda" type="text" asp-for="RendaValor" class="form-control" placeholder="Digite a renda">
        @Html.ValidationMessageFor(x => x.RendaValor, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="cpf" class="form-label">CPF:</label>
        <input type="text" asp-for="CPF" id="cpf" class="form-control" placeholder="Digite o CPF">
        @Html.ValidationMessageFor(x => x.CPF, "", new { @class = "text-danger" })
    </div>    

    <button type="submit" class="btn btn-primary btn-block">Salvar</button>    
    <a class="btn btn-secondary btn-block" asp-controller="Pessoa" asp-action="Index" role="button">Voltar</a>
</form>

@*Formatação de CPF*@
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#cpf').on('input', function () {
            var cpf = $(this).val();
            cpf = cpf.replace(/\D/g, ''); // Removendo todos os caracteres não numéricos

            if (cpf.length > 11) {
                cpf = cpf.slice(0, 11); // Limita o tamanho máximo do CPF a 11 caracteres
            }

            // Formatação do CPF
            cpf = cpf.replace(/(\d{3})(\d)/, '$1.$2');
            cpf = cpf.replace(/(\d{3})(\d)/, '$1.$2');
            cpf = cpf.replace(/(\d{3})(\d{1,2})$/, '$1-$2');

            // Atualiza o valor do campo de entrada
            $(this).val(cpf);
        });

        $("#renda").on("input", function () {
            var valor = $(this).val();

            // Remove qualquer caractere que não seja número
            valor = valor.replace(/[^0-9]/g, '');

            // Atualiza o valor do campo com a versão filtrada
            $(this).val(valor);
        });
    });
</script>

Views/Pessoa/Index.cshtml
@model List<Pessoa>

@{
    ViewData["Title"] = "Pessoas";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Pessoa" asp-action="Create">Cadastro de Pessoas</a>
    </div>
    <br>

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Pessoas Cadastro</h1>
    <br>


    <table class="table" id="tabelaDados">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nome</th>
                <th scope="col">DataNascimento</th>
                <th scope="col">CPF</th>
                <th scope="col">Renda</th>
                <th scope="col">Opções</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any()) // contém algo?
            {
                foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td>@item.NomeCompleto</td>
                        <td>@item.DataNascimento</td>
                        <td>@item.CPF</td>
                        <td>@item.RendaValor</td>
                        <td>
                            <div class="bd-example" role="group">
                                <a href="@Url.Action("Edit", "Pessoa", new { item.Id })" class="btn btn-outline-warning btn-lg" role="button" aria-disabled="true">Alterar</a>
                                <a href="@Url.Action("Delete", "Pessoa", new { item.Id })" class="btn btn-outline-danger btn-lg" role="button" aria-disabled="true">Excluir</a>                                
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>